2022-12-13 21:21:31,152 INFO Запись успешно добавлена в таблицy
2022-12-13 21:21:36,156 INFO Запись успешно добавлена в таблицy
2022-12-13 21:21:41,160 INFO Запись успешно добавлена в таблицy
2022-12-13 21:21:46,163 INFO Запись успешно добавлена в таблицy
2022-12-13 21:21:51,167 INFO Запись успешно добавлена в таблицy
2022-12-13 21:21:51,307 ERROR Connection issue while reading from PostgreSQL
Traceback (most recent call last):
  File "C:\Users\roman\PycharmProjects\mqtt_messages\postgre_get_data.py", line 46, in connect_now
    connect_now()
  File "C:\Users\roman\PycharmProjects\mqtt_messages\postgre_get_data.py", line 34, in connect_now
    a = int(input('Update data 1/0?'))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
2022-12-13 21:21:56,170 INFO Запись успешно добавлена в таблицy
2022-12-13 21:22:01,173 INFO Запись успешно добавлена в таблицy
2022-12-13 21:22:06,176 INFO Запись успешно добавлена в таблицy
2022-12-13 21:22:11,180 INFO Запись успешно добавлена в таблицy
2022-12-13 21:22:16,184 INFO Запись успешно добавлена в таблицy
2022-12-13 21:22:21,187 INFO Запись успешно добавлена в таблицy
2022-12-13 21:22:26,191 INFO Запись успешно добавлена в таблицy
2022-12-13 21:22:36,194 INFO Запись успешно добавлена в таблицy
2022-12-13 21:22:41,197 INFO Запись успешно добавлена в таблицy
2022-12-13 21:22:46,201 INFO Запись успешно добавлена в таблицy
2022-12-13 21:22:56,204 INFO Запись успешно добавлена в таблицy
2022-12-13 21:23:06,208 INFO Запись успешно добавлена в таблицy
2022-12-13 21:23:11,213 INFO Запись успешно добавлена в таблицy
2022-12-13 21:23:16,216 INFO Запись успешно добавлена в таблицy
2022-12-13 21:23:21,218 INFO Запись успешно добавлена в таблицy
